collections_config:
  commercial:
    path: surge
    icon: camera
    url: /[slug]
    disable_url: false
    _enabled_editors:
      - visual
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Etc/UTC
static_site_generator: none
build:
  command: echo "Serving static files directly"
output_path: /
